name: scanservjs
version: "0.1.1"
slug: scanservjs
description: Scanner USB via SANE et interface web
arch: [aarch64, amd64]
init: false
usb: true
privileged: [SYS_RAWIO]
map:
  - share:rw
startup: application
ingress: true
ingress_port: 8080
panel_icon: mdi:scanner
panel_title: Scanner
panel_admin: false